name: geocoding_web
description: Web platform implementation of geocoding
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: geocoding
    platforms:
      web:
        pluginClass: GeocodingPlugin
        fileName: geocoding_web.dart


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter 
  geocoding_platform_interface: 
    path: ../geocoding_platform_interface
  http: ^0.13.3
  js: ^0.6.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  plugin_platform_interface: ^2.0.0

